version: '3.6'
services:
  spells:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      ECTO_DATABASE_URL: ecto://postgres:postgres@postgres/spellbook_dev
      ECTO_TEST_DATABASE_URL: ecto://postgres:postgres@postgres/spellbook_dev
    links:
      - postgres
    ports:
      - "4000:4000"
    volumes:
      - .:/code
      - spells-build:/code/_build
      - spells-deps:/code/deps
  postgres:
    image: "postgres:11-alpine"
    environment:
      POSTGRES_DB: spellbook_dev
    ports:
      - "5432:5432"
    volumes:
      - .:/code
      - db:/var/lib/postgresql/data
volumes:
  spells-build:
  spells-deps:
  db:

